#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='subl'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_NZ.UTF-8'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

export GOPATH="$HOME/projects/golang"

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/packer/current
  /usr/local/terraform/bin
  /usr/local/heroku/bin
  /usr/local/share/npm/bin
  /usr/local/opt/go/libexec/bin
  /usr/local/{bin,sbin}
  $path
  $GOPATH/bin
  $HOME/.node/bin
  /opt/chefdk/embedded/bin
  ~/.bin
)

fpath=(
  /usr/local/share/zsh/site-functions
  $fpath
)

# Boot2docker connection
export DOCKER_TLS_VERIFY=1
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH="$HOME/.boot2docker/certs/boot2docker-vm"

# use vagrant with vmware whenever possible
export VAGRANT_DEFAULT_PROVIDER=vmware_fusion

# OS X 10.9 XCode 5.1 workaround
export ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future

# RBENV user install
export RBENV_ROOT="$HOME/.rbenv"

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi
