#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customizations:

# Aliases
alias zshconfig="${EDITOR} ~/.zshrc"
alias grm="git ls-files -z --deleted | xargs -0r git rm" # git rm files that are manually deleted
alias reload!='. ~/.zshrc'
alias rand='openssl rand -base64 10'
alias atom='nocorrect atom'

# Not everything should be on github...
if [[ -s ~/.zprivatenv ]]; then
  source ~/.zprivatenv
fi

# Don't autocorrect me
unsetopt correct_all

# pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
export PATH=/opt/chefdk/embedded/bin:$PATH # Ensure chef-dk is ahead of rbenv ruby installed binaries in the path

# . "${RBENV_ROOT}/completions/rbenv.zsh"
# rbenv rehash 2>/dev/null

# autocomplete ssh based on ~/.ssh/config
hosts=$(awk '/^Host / {printf("%s ",$2)}' ~/.ssh/config 2>/dev/null)
zstyle ':completion:*:hosts' hosts '$hosts'

# show completion menu when number of options is at least 2
zstyle ':completion:*' menu select=2


# Travis gem autocomplete
if [[ -s "${ZDOTDIR:-$HOME}/.travis/travis.sh" ]]; then
  source "${ZDOTDIR:-$HOME}/.travis/travis.sh"
fi
